---
- hosts: appserver
  gather_facts: false
  tasks:
  - name: install dbserver
    apt: name=mariadb-server state=latest
  - name: ensure dbserver is running
    service: name=mysql state=running

- hosts: webserver
  roles:
  - webserver
  - firewall   

  tasks:
  - name: install webserver application
    apt: name=apache2 state=latest
  - name: ensure webserver service is running
    service: name=apache2 state=running

