---
- hosts: appserver
  tasks:
  - name: install dbserver
    apt: name=mariadb-server state=latest
  - name: ensure dbserver is running
    service: name=mysql state=running

- hosts: webserver
  roles:
  - webserver
  - firewall   

